### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by aesycos** [Mrcuve0/Silicon#1]
Resource links for several resources are broken, this includes:
- Color Scheme Silicon
- Wallpapers
- Plasma Theme
- Plasma Theme Opaque
- Aurorae Theme

**Comment by Mrcuve0** [comment]
Thank you for your feedback!
I solved the problem right now: I forgot to remove those links when I made the previous commit.

I deleted the link to the Aurorae and Firefox Themes since they are not ready to be released for now. I'll add them of course when I'll upload the source code.

Sorry for the folder related to the "plasmaScheme Opaque" that I also erroneously pushed last time: for now consider it just as a placeholder since, as you can see, it refers to the "Aritim Dark" theme (as the folder structure is the same)

Hope you are enjoying Silicon! :)
