### ISSUE TITLE
Clean Documentation

### ISSUE THREAD

**Issue by mateusfg7** [Mrcuve0/Silicon#2]
**Is your feature request related to a problem? Please describe.**
bad documentation

**Describe the solution you'd like**
make the documentation clearer

**Describe alternatives you've considered**
make a wepage for this project and others.

**Additional context**
I'm not able to find the documentation with the project's dependencies, nor the subfolders, could you make the documentation clearer?

**Comment by Mrcuve0** [comment]
This repository is intended as both a "showcase" webpage to my theme (that's why I have included at least 2 screenshots per theme) and as "a big box" where I can place all the files and components of an entire theme. I previously dealt in the past with multiple repositories for each theme but this caused an even more cluttered workspace and additional difficulty and time wasted to organize and update all the READMEs.

Additional information on how to install the theme and all the dependencies can be found for example in the `lookAndFeel` subfolder (https://github.com/Mrcuve0/Silicon/tree/master/KDE/lookAndFeel). (Basically, most of the information a user needs can be found by clicking on each subfolder of the project).
Click on the `KDE` folder to see all the components related to the KDE version of the theme.
As for now, there are no additional components because this theme, unlike Aritim-Dark/Light, is still under development (not a lot of spare time to concentrate on it)

Although I'm considering the idea of a personal website, I also think that, for now, having a GitHub page, an [OpenDesktop](https://www.pling.com/u/mrcuve0/) account and a Twitter account is sufficient.

Finally, to me, the documentation is pretty clear if someone is willing to navigate the subfolders. 
Also, a theme does not need so much documentation (because, basically, it's a theme, not a 100+ developers project). Basically, I don't know what additional informations I could add. 

Thank you for your time.
